# Form implementation generated from reading ui file 'c:\Users\ryanj\OneDrive\Desktop\PD2gui\pop_forms\changepass.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt6 import QtCore, QtGui, QtWidgets

MAIN_PATH = os.getcwd()
IMAGES_PATH = os.path.join(MAIN_PATH, 'image')


class Ui_ChangePassWindow(object):
    def setupUi(self, ChangePassWindow):
        ChangePassWindow.setObjectName("ChangePassWindow")
        ChangePassWindow.resize(480, 600)
        ChangePassWindow.setMinimumSize(QtCore.QSize(480, 600))
        ChangePassWindow.setMaximumSize(QtCore.QSize(480, 600))
        self.centralwidget = QtWidgets.QWidget(parent=ChangePassWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 20, 151, 151))
        self.label.setPixmap(QtGui.QPixmap(os.path.join(IMAGES_PATH, "check.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verificationtxt = QtWidgets.QLabel(parent=self.centralwidget)
        self.verificationtxt.setGeometry(QtCore.QRect(150, 180, 171, 51))
        self.verificationtxt.setStyleSheet("font: 700 21pt \"Tahoma\";")
        self.verificationtxt.setObjectName("verificationtxt")
        self.instrtxt_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.instrtxt_2.setGeometry(QtCore.QRect(150, 220, 181, 51))
        self.instrtxt_2.setStyleSheet("font: 13pt \"Tahoma\";")
        self.instrtxt_2.setObjectName("instrtxt_2")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 481, 601))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.newpassset = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.newpassset.setGeometry(QtCore.QRect(50, 360, 381, 51))
        self.newpassset.setAutoFillBackground(False)
        self.newpassset.setStyleSheet("font: 12pt \"Tahoma\";\n"
"background-color: rgb(227, 227, 227);\n"
"border: 0.5px solid black;\n"
"border-radius: 10px;\n"
"padding: 5px;")
        self.newpassset.setMaxLength(30)
        self.newpassset.setFrame(True)
        self.newpassset.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.newpassset.setPlaceholderText("New Password")
        self.newpassset.setObjectName("newpassset")
        self.changepassset = QtWidgets.QPushButton(parent=self.centralwidget)
        self.changepassset.setGeometry(QtCore.QRect(60, 510, 171, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changepassset.sizePolicy().hasHeightForWidth())
        self.changepassset.setSizePolicy(sizePolicy)
        self.changepassset.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.changepassset.setAutoFillBackground(False)
        self.changepassset.setStyleSheet("#changepassset {\n"
"background-color: rgb(85, 183, 221);\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"color: white;\n"
"}\n"
"\n"
"#changepassset:Hover {\n"
"background-color: rgb(16, 170, 215);\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"color: white;\n"
"}\n"
"\n"
"#changepassset:Pressed {\n"
"background-color: rgb(16, 170, 163);\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"color: white;\n"
"}")
        self.changepassset.setChecked(False)
        self.changepassset.setAutoDefault(True)
        self.changepassset.setObjectName("changepassset")
        self.confirm_newsetpass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.confirm_newsetpass.setGeometry(QtCore.QRect(50, 440, 381, 51))
        self.confirm_newsetpass.setAutoFillBackground(False)
        self.confirm_newsetpass.setStyleSheet("font: 12pt \"Tahoma\";\n"
"background-color: rgb(227, 227, 227);\n"
"border: 0.5px solid black;\n"
"border-radius: 10px;\n"
"padding: 5px;")
        self.confirm_newsetpass.setMaxLength(30)
        self.confirm_newsetpass.setFrame(True)
        self.confirm_newsetpass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.confirm_newsetpass.setPlaceholderText("Confirm New Password")
        self.confirm_newsetpass.setObjectName("confirm_newsetpass")
        self.confpasssetreveal = QtWidgets.QLabel(parent=self.centralwidget)
        self.confpasssetreveal.setGeometry(QtCore.QRect(390, 450, 31, 31))
        self.confpasssetreveal.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.confpasssetreveal.setText("")
        self.confpasssetreveal.setPixmap(QtGui.QPixmap(os.path.join(IMAGES_PATH,'invisible.png')))
        self.confpasssetreveal.setScaledContents(True)
        self.confpasssetreveal.setObjectName("confpasssetreveal")
        self.newpasssetreveal = QtWidgets.QLabel(parent=self.centralwidget)
        self.newpasssetreveal.setGeometry(QtCore.QRect(390, 370, 31, 31))
        self.newpasssetreveal.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.newpasssetreveal.setText("")
        self.newpasssetreveal.setPixmap(QtGui.QPixmap(os.path.join(IMAGES_PATH,'invisible.png')))
        self.newpasssetreveal.setScaledContents(True)
        self.newpasssetreveal.setObjectName("newpasssetreveal")
        self.oldpassset = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.oldpassset.setGeometry(QtCore.QRect(50, 280, 381, 51))
        self.oldpassset.setAutoFillBackground(False)
        self.oldpassset.setStyleSheet("font: 12pt \"Tahoma\";\n"
"background-color: rgb(227, 227, 227);\n"
"border: 0.5px solid black;\n"
"border-radius: 10px;\n"
"padding: 5px;")
        self.oldpassset.setMaxLength(30)
        self.oldpassset.setFrame(True)
        self.oldpassset.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.oldpassset.setPlaceholderText("Old Password")
        self.oldpassset.setObjectName("oldpassset")
        self.revealoldpass = QtWidgets.QLabel(parent=self.centralwidget)
        self.revealoldpass.setGeometry(QtCore.QRect(390, 290, 31, 31))
        self.revealoldpass.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.revealoldpass.setText("")
        self.revealoldpass.setPixmap(QtGui.QPixmap(os.path.join(IMAGES_PATH,'invisible.png')))
        self.revealoldpass.setScaledContents(True)
        self.revealoldpass.setObjectName("revealoldpass")
        self.changepasscancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.changepasscancel.setGeometry(QtCore.QRect(250, 510, 171, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changepasscancel.sizePolicy().hasHeightForWidth())
        self.changepasscancel.setSizePolicy(sizePolicy)
        self.changepasscancel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.changepasscancel.setAutoFillBackground(False)
        self.changepasscancel.setStyleSheet("#changepasscancel {\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"border: 1px solid gray;\n"
"color: black\n"
"}\n"
"#changepasscancel:Hover {\n"
"background-color: gray;\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"border: 1px solid gray;\n"
"color: white;\n"
"}\n"
"#changepasscancel:Pressed {\n"
"background-color: rgb(143, 143, 143);\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"border: 1px solid gray;\n"
"color: white;\n"
"}")
        self.changepasscancel.setChecked(False)
        self.changepasscancel.setAutoDefault(True)
        self.changepasscancel.setObjectName("changepasscancel")
        self.label_2.raise_()
        self.verificationtxt.raise_()
        self.instrtxt_2.raise_()
        self.newpassset.raise_()
        self.changepassset.raise_()
        self.confirm_newsetpass.raise_()
        self.confpasssetreveal.raise_()
        self.newpasssetreveal.raise_()
        self.label.raise_()
        self.oldpassset.raise_()
        self.revealoldpass.raise_()
        self.changepasscancel.raise_()
        ChangePassWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ChangePassWindow)
        QtCore.QMetaObject.connectSlotsByName(ChangePassWindow)

    def retranslateUi(self, ChangePassWindow):
        _translate = QtCore.QCoreApplication.translate
        ChangePassWindow.setWindowTitle(_translate("ChangePassWindow", "Change Password"))
        self.verificationtxt.setText(_translate("ChangePassWindow", " Verification"))
        self.instrtxt_2.setText(_translate("ChangePassWindow", "Set Your New Password"))
        self.changepassset.setText(_translate("ChangePassWindow", "Confirm"))
        self.changepasscancel.setText(_translate("ChangePassWindow", "Cancel"))
