# Form implementation generated from reading ui file 'c:\Users\ryanj\OneDrive\Desktop\PD2gui\pop_forms\datapolicy.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dataprivacy(object):
    def setupUi(self, dataprivacy):
        dataprivacy.setObjectName("dataprivacy")
        dataprivacy.resize(580, 750)
        dataprivacy.setMinimumSize(QtCore.QSize(580, 750))
        dataprivacy.setMaximumSize(QtCore.QSize(580, 750))
        self.centralwidget = QtWidgets.QWidget(parent=dataprivacy)
        self.centralwidget.setStyleSheet("#centralwidget {\n"
"background-color: white;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.policy = QtWidgets.QTextEdit(parent=self.widget)
        self.policy.setReadOnly(True)
        self.policy.setObjectName("policy")
        self.verticalLayout.addWidget(self.policy)
        self.checkboxwidget = QtWidgets.QWidget(parent=self.widget)
        self.checkboxwidget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.checkboxwidget.setObjectName("checkboxwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.checkboxwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.agreecheckBox = QtWidgets.QCheckBox(parent=self.checkboxwidget)
        self.agreecheckBox.setObjectName("agreecheckBox")
        self.verticalLayout_2.addWidget(self.agreecheckBox, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout.addWidget(self.checkboxwidget)
        self.buttons = QtWidgets.QWidget(parent=self.widget)
        self.buttons.setMaximumSize(QtCore.QSize(16777215, 50))
        self.buttons.setObjectName("buttons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttons)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Proceed = QtWidgets.QPushButton(parent=self.buttons)
        self.Proceed.setMinimumSize(QtCore.QSize(100, 40))
        self.Proceed.setObjectName("Proceed")
        self.horizontalLayout.addWidget(self.Proceed)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.Cancelagree = QtWidgets.QPushButton(parent=self.buttons)
        self.Cancelagree.setMinimumSize(QtCore.QSize(100, 40))
        self.Cancelagree.setObjectName("Cancelagree")
        self.horizontalLayout.addWidget(self.Cancelagree)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.buttons)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        dataprivacy.setCentralWidget(self.centralwidget)

        self.retranslateUi(dataprivacy)
        QtCore.QMetaObject.connectSlotsByName(dataprivacy)

    def retranslateUi(self, dataprivacy):
        _translate = QtCore.QCoreApplication.translate
        dataprivacy.setWindowTitle(_translate("dataprivacy", "Data Privacy Policy"))
        self.policy.setHtml(_translate("dataprivacy", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:700;\">Data Privacy Acknowledgment and Agreement Policy</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:700;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">1. Introduction</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">This Data Privacy Acknowledgment and Agreement (&quot;Agreement&quot;) outlines the terms and conditions under which your (&quot;you&quot;) personal data will be collected, used, and protected by InquestAI (&quot;we&quot;). By using our services, you acknowledge and agree to the practices described in this Agreement.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">2. Data Collection</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:700;\">2.1</span><span style=\" font-size:10pt;\"> User Account Creation: To create and manage user accounts on our platform, including user authentication, password recovery, and account customization.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:700;\">2.2</span><span style=\" font-size:10pt;\"> Communication: To send important notifications, updates, and communications to users, including account-related information, and service announcements.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:700;\">2.3 </span><span style=\" font-size:10pt;\">Customer Support: To provide customer support and assistance, including responding to inquiries, resolving issues, and offering technical assistance.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:700;\">2.4 </span><span style=\" font-size:10pt;\">Legal Compliance: To fulfill legal and regulatory requirements, such as identity verification, fraud prevention, and compliance with applicable data protection laws.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">3. Data Usage</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Your personal data will be used only for the purposes stated in section 2 and in accordance with applicable data protection laws.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">4. Data Protection</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">We are committed to protecting your personal data and will take reasonable measures to safeguard it from unauthorized access, disclosure, alteration, or destruction.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">5. Data Sharing</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Your personal data will not be shared with third parties without your explicit consent, except when required by law.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">6. Data Retention</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">We will retain your personal data for as long as necessary to fulfill the purposes outlined in section 2 or as required by applicable laws.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">7. Your Rights</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">You have the right to access, rectify, delete, or restrict the processing of your personal data. You can exercise these rights by contacting us at </span><span style=\" font-size:10pt; font-weight:700;\">inquestai.recovery@gmail.com</span><span style=\" font-size:10pt;\">.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">8. Changes to this Agreement</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">We may update this Agreement from time to time to reflect changes in our data handling practices. Any significant changes will be communicated to you.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">9. Contact Information</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">If you have any questions or concerns regarding your data privacy or this Agreement, please contact us at </span><span style=\" font-size:10pt; font-weight:700;\">inquestai.recovery@gmail.com</span><span style=\" font-size:10pt;\">.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-style:italic;\">By using our services, you acknowledge that you have read and understood this Agreement and agree to the collection, use, and protection of your personal data as described herein.</span></p></body></html>"))
        self.agreecheckBox.setText(_translate("dataprivacy", "I acknowledge that I have read and understood the data privacy policy."))
        self.Proceed.setText(_translate("dataprivacy", "Proceed"))
        self.Cancelagree.setText(_translate("dataprivacy", "Cancel"))
