# Form implementation generated from reading ui file 'c:\Users\ryanj\OneDrive\Desktop\PD2gui\pop_forms\forgotpass.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Reset(object):
    def setupUi(self, Reset):
        Reset.setObjectName("Reset")
        Reset.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        Reset.resize(600, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Reset.sizePolicy().hasHeightForWidth())
        Reset.setSizePolicy(sizePolicy)
        Reset.setMinimumSize(QtCore.QSize(600, 400))
        Reset.setMaximumSize(QtCore.QSize(600, 400))
        self.centralwidget = QtWidgets.QWidget(parent=Reset)
        self.centralwidget.setObjectName("centralwidget")
        self.whitebg = QtWidgets.QLabel(parent=self.centralwidget)
        self.whitebg.setGeometry(QtCore.QRect(0, 0, 601, 401))
        self.whitebg.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.whitebg.setText("")
        self.whitebg.setObjectName("whitebg")
        self.findaccttxt = QtWidgets.QLabel(parent=self.centralwidget)
        self.findaccttxt.setGeometry(QtCore.QRect(40, 40, 291, 31))
        self.findaccttxt.setStyleSheet("font: 700 23pt \"Tahoma\";")
        self.findaccttxt.setObjectName("findaccttxt")
        self.instrtxt_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.instrtxt_2.setGeometry(QtCore.QRect(70, 90, 461, 51))
        self.instrtxt_2.setStyleSheet("font: 15pt \"Tahoma\";")
        self.instrtxt_2.setObjectName("instrtxt_2")
        self.forgotpassem = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.forgotpassem.setGeometry(QtCore.QRect(90, 170, 421, 51))
        self.forgotpassem.setAutoFillBackground(False)
        self.forgotpassem.setStyleSheet("font: 12pt \"Tahoma\";\n"
"background-color: rgb(227, 227, 227);\n"
"border: 0.5px solid black;\n"
"border-radius: 10px;\n"
"padding: 15px;")
        self.forgotpassem.setText("")
        self.forgotpassem.setMaxLength(30)
        self.forgotpassem.setFrame(True)
        self.forgotpassem.setClearButtonEnabled(False)
        self.forgotpassem.setObjectName("forgotpassem")
        self.searchforgot = QtWidgets.QPushButton(parent=self.centralwidget)
        self.searchforgot.setGeometry(QtCore.QRect(150, 260, 131, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchforgot.sizePolicy().hasHeightForWidth())
        self.searchforgot.setSizePolicy(sizePolicy)
        self.searchforgot.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.searchforgot.setAutoFillBackground(False)
        self.searchforgot.setStyleSheet("#searchforgot {\n"
"background-color: rgb(85, 183, 221);\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"color: white;\n"
"}\n"
"\n"
"#searchforgot:Hover {\n"
"background-color: rgb(16, 170, 215);\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"color: white;\n"
"}\n"
"\n"
"#searchforgot:Pressed {\n"
"background-color: rgb(16, 170, 163);\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"color: white;\n"
"}")
        self.searchforgot.setChecked(False)
        self.searchforgot.setAutoDefault(True)
        self.searchforgot.setObjectName("searchforgot")
        self.cancelforgot = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cancelforgot.setGeometry(QtCore.QRect(320, 260, 131, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelforgot.sizePolicy().hasHeightForWidth())
        self.cancelforgot.setSizePolicy(sizePolicy)
        self.cancelforgot.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancelforgot.setAutoFillBackground(False)
        self.cancelforgot.setStyleSheet("#cancelforgot {\n"
"background-color: rgb(85, 183, 221);\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"color: white;\n"
"}\n"
"\n"
"#cancelforgot:Hover {\n"
"background-color: rgb(16, 170, 215);\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"color: white;\n"
"}\n"
"\n"
"#cancelforgot:Pressed {\n"
"background-color: rgb(16, 170, 163);\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"color: white;\n"
"}")
        self.cancelforgot.setChecked(False)
        self.cancelforgot.setAutoDefault(True)
        self.cancelforgot.setObjectName("cancelforgot")
        Reset.setCentralWidget(self.centralwidget)

        self.retranslateUi(Reset)
        QtCore.QMetaObject.connectSlotsByName(Reset)

    def retranslateUi(self, Reset):
        _translate = QtCore.QCoreApplication.translate
        Reset.setWindowTitle(_translate("Reset", "Reset"))
        self.findaccttxt.setText(_translate("Reset", "Find your account"))
        self.instrtxt_2.setText(_translate("Reset", "Please enter your email to search for your account."))
        self.forgotpassem.setPlaceholderText(_translate("Reset", "Email"))
        self.searchforgot.setText(_translate("Reset", "Search"))
        self.cancelforgot.setText(_translate("Reset", "Cancel"))
