# Form implementation generated from reading ui file 'c:\Users\ryanj\OneDrive\Desktop\PD2gui\pop_forms\OTPReg.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt6 import QtCore, QtGui, QtWidgets

MAIN_PATH = os.getcwd()
IMAGES_PATH = os.path.join(MAIN_PATH, 'image')


class Ui_OTPWindow(object):
    def setupUi(self, OTPWindow):
        OTPWindow.setObjectName("OTPWindow")
        OTPWindow.resize(480, 600)
        OTPWindow.setMinimumSize(QtCore.QSize(480, 600))
        OTPWindow.setMaximumSize(QtCore.QSize(480, 600))
        self.centralwidget = QtWidgets.QWidget(parent=OTPWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.confirmotp = QtWidgets.QPushButton(parent=self.centralwidget)
        self.confirmotp.setGeometry(QtCore.QRect(60, 420, 171, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confirmotp.sizePolicy().hasHeightForWidth())
        self.confirmotp.setSizePolicy(sizePolicy)
        self.confirmotp.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.confirmotp.setAutoFillBackground(False)
        self.confirmotp.setStyleSheet("#confirmotp {\n"
"background-color: rgb(85, 183, 221);\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"color: white;\n"
"}\n"
"\n"
"#confirmotp:Hover {\n"
"background-color: rgb(16, 170, 215);\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"color: white;\n"
"}\n"
"\n"
"#confirmotp:Pressed {\n"
"background-color: rgb(16, 170, 163);\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"color: white;\n"
"}")
        self.confirmotp.setChecked(False)
        self.confirmotp.setAutoDefault(True)
        self.confirmotp.setObjectName("confirmotp")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 60, 151, 151))
        self.label.setPixmap(QtGui.QPixmap(os.path.join(IMAGES_PATH, "check.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.findaccttxt_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.findaccttxt_2.setGeometry(QtCore.QRect(150, 210, 171, 51))
        self.findaccttxt_2.setStyleSheet("font: 700 21pt \"Tahoma\";")
        self.findaccttxt_2.setObjectName("findaccttxt_2")
        self.instrtxt_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.instrtxt_2.setGeometry(QtCore.QRect(70, 260, 361, 51))
        self.instrtxt_2.setStyleSheet("font: 13pt \"Tahoma\";")
        self.instrtxt_2.setObjectName("instrtxt_2")
        self.otpenter = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.otpenter.setGeometry(QtCore.QRect(50, 330, 381, 51))
        self.otpenter.setAutoFillBackground(False)
        self.otpenter.setStyleSheet("font: 12pt \"Tahoma\";\n"
"background-color: rgb(227, 227, 227);\n"
"border: 0.5px solid black;\n"
"border-radius: 10px;\n"
"padding: 5px;")
        self.otpenter.setMaxLength(6)
        self.otpenter.setFrame(True)
        self.otpenter.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.otpenter.setPlaceholderText("One Time Password")
        self.otpenter.setObjectName("otpenter")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 481, 601))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.cancelreg = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cancelreg.setGeometry(QtCore.QRect(250, 420, 171, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelreg.sizePolicy().hasHeightForWidth())
        self.cancelreg.setSizePolicy(sizePolicy)
        self.cancelreg.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancelreg.setAutoFillBackground(False)
        self.cancelreg.setStyleSheet("#cancelreg {\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"border: 1px solid gray;\n"
"color: black\n"
"}\n"
"#cancelreg:Hover {\n"
"background-color: gray;\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"border: 1px solid gray;\n"
"color: white;\n"
"}\n"
"#cancelreg:Pressed {\n"
"background-color: rgb(143, 143, 143);\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"border: 1px solid gray;\n"
"color: white;\n"
"}")
        self.cancelreg.setChecked(False)
        self.cancelreg.setAutoDefault(True)
        self.cancelreg.setObjectName("cancelreg")
        self.label_2.raise_()
        self.confirmotp.raise_()
        self.label.raise_()
        self.findaccttxt_2.raise_()
        self.instrtxt_2.raise_()
        self.otpenter.raise_()
        self.cancelreg.raise_()
        OTPWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(OTPWindow)
        QtCore.QMetaObject.connectSlotsByName(OTPWindow)

    def retranslateUi(self, OTPWindow):
        _translate = QtCore.QCoreApplication.translate
        OTPWindow.setWindowTitle(_translate("OTPWindow", "Confirm Registration"))
        self.confirmotp.setText(_translate("OTPWindow", "Confirm"))
        self.findaccttxt_2.setText(_translate("OTPWindow", " Verification"))
        self.instrtxt_2.setText(_translate("OTPWindow", "Check your email for your One Time Password"))
        self.cancelreg.setText(_translate("OTPWindow", "Cancel"))
