# Form implementation generated from reading ui file 'c:\Users\ryanj\OneDrive\Desktop\PD2gui\pop_forms\updatepass.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt6 import QtCore, QtGui, QtWidgets

MAIN_PATH = os.getcwd()
IMAGES_PATH = os.path.join(MAIN_PATH, 'image')


class Ui_updatesettings(object):
    def setupUi(self, updatesettings):
        updatesettings.setObjectName("updatesettings")
        updatesettings.resize(480, 600)
        updatesettings.setMinimumSize(QtCore.QSize(480, 600))
        updatesettings.setMaximumSize(QtCore.QSize(480, 600))
        self.centralwidget = QtWidgets.QWidget(parent=updatesettings)
        self.centralwidget.setObjectName("centralwidget")
        self.confirmsetpass = QtWidgets.QPushButton(parent=self.centralwidget)
        self.confirmsetpass.setGeometry(QtCore.QRect(60, 410, 171, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confirmsetpass.sizePolicy().hasHeightForWidth())
        self.confirmsetpass.setSizePolicy(sizePolicy)
        self.confirmsetpass.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.confirmsetpass.setAutoFillBackground(False)
        self.confirmsetpass.setStyleSheet("#confirmsetpass {\n"
"background-color: rgb(85, 183, 221);\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"color: white;\n"
"}\n"
"\n"
"#confirmsetpass:Hover {\n"
"background-color: rgb(16, 170, 215);\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"color: white;\n"
"}\n"
"\n"
"#confirmsetpass:Pressed {\n"
"background-color: rgb(16, 170, 163);\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"color: white;\n"
"}")
        self.confirmsetpass.setChecked(False)
        self.confirmsetpass.setAutoDefault(True)
        self.confirmsetpass.setObjectName("confirmsetpass")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 60, 151, 151))
        self.label.setPixmap(QtGui.QPixmap(os.path.join(IMAGES_PATH, "check.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.findaccttxt_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.findaccttxt_2.setGeometry(QtCore.QRect(150, 210, 171, 51))
        self.findaccttxt_2.setStyleSheet("font: 700 21pt \"Tahoma\";")
        self.findaccttxt_2.setObjectName("findaccttxt_2")
        self.instrtxt_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.instrtxt_2.setGeometry(QtCore.QRect(70, 260, 361, 51))
        self.instrtxt_2.setStyleSheet("font: 11pt \"Tahoma\";")
        self.instrtxt_2.setObjectName("instrtxt_2")
        self.updateactsetpass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.updateactsetpass.setGeometry(QtCore.QRect(50, 330, 381, 51))
        self.updateactsetpass.setAutoFillBackground(False)
        self.updateactsetpass.setStyleSheet("font: 12pt \"Tahoma\";\n"
"background-color: rgb(227, 227, 227);\n"
"border: 0.5px solid black;\n"
"border-radius: 10px;\n"
"padding: 5px;")
        self.updateactsetpass.setMaxLength(15)
        self.updateactsetpass.setFrame(True)
        self.updateactsetpass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.updateactsetpass.setPlaceholderText("Password")
        self.updateactsetpass.setObjectName("updateactsetpass")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 481, 601))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.newpassreveal = QtWidgets.QLabel(parent=self.centralwidget)
        self.newpassreveal.setGeometry(QtCore.QRect(390, 340, 31, 31))
        self.newpassreveal.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.newpassreveal.setText("")
        self.newpassreveal.setPixmap(QtGui.QPixmap(os.path.join(IMAGES_PATH, "invisible.png")))
        self.newpassreveal.setScaledContents(True)
        self.newpassreveal.setObjectName("newpassreveal")
        self.updatepasscancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.updatepasscancel.setGeometry(QtCore.QRect(250, 410, 171, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updatepasscancel.sizePolicy().hasHeightForWidth())
        self.updatepasscancel.setSizePolicy(sizePolicy)
        self.updatepasscancel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.updatepasscancel.setAutoFillBackground(False)
        self.updatepasscancel.setStyleSheet("#updatepasscancel {\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"border: 1px solid gray;\n"
"color: black\n"
"}\n"
"#updatepasscancel:Hover {\n"
"background-color: gray;\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"border: 1px solid gray;\n"
"color: white;\n"
"}\n"
"#updatepasscancel:Pressed {\n"
"background-color: rgb(143, 143, 143);\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"border: 1px solid gray;\n"
"color: white;\n"
"}")
        self.updatepasscancel.setChecked(False)
        self.updatepasscancel.setAutoDefault(True)
        self.updatepasscancel.setObjectName("updatepasscancel")
        self.label_2.raise_()
        self.confirmsetpass.raise_()
        self.label.raise_()
        self.findaccttxt_2.raise_()
        self.instrtxt_2.raise_()
        self.updateactsetpass.raise_()
        self.newpassreveal.raise_()
        self.updatepasscancel.raise_()
        updatesettings.setCentralWidget(self.centralwidget)

        self.retranslateUi(updatesettings)
        QtCore.QMetaObject.connectSlotsByName(updatesettings)

    def retranslateUi(self, updatesettings):
        _translate = QtCore.QCoreApplication.translate
        updatesettings.setWindowTitle(_translate("updatesettings", "Enter Password"))
        self.confirmsetpass.setText(_translate("updatesettings", "Confirm"))
        self.findaccttxt_2.setText(_translate("updatesettings", " Verification"))
        self.instrtxt_2.setText(_translate("updatesettings", "Enter your password to update your account settings"))
        self.updatepasscancel.setText(_translate("updatesettings", "Cancel"))
