# Form implementation generated from reading ui file 'c:\Users\ryanj\OneDrive\Desktop\PD2gui\notif_ui\expired_otp.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt6 import QtCore, QtGui, QtWidgets

MAIN_PATH = os.getcwd()
IMAGES_PATH = os.path.join(MAIN_PATH, 'image')

class Ui_expiredotp(object):
    def setupUi(self, expiredotp):
        expiredotp.setObjectName("expiredotp")
        expiredotp.resize(370, 200)
        expiredotp.setMinimumSize(QtCore.QSize(370, 200))
        expiredotp.setMaximumSize(QtCore.QSize(370, 200))
        self.centralwidget = QtWidgets.QWidget(parent=expiredotp)
        self.centralwidget.setMinimumSize(QtCore.QSize(370, 200))
        self.centralwidget.setMaximumSize(QtCore.QSize(370, 200))
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 111, 111))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(os.path.join(IMAGES_PATH, "expired.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.ok_otpexpired = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ok_otpexpired.setGeometry(QtCore.QRect(270, 150, 81, 41))
        self.ok_otpexpired.setObjectName("ok_otpexpired")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 50, 241, 71))
        self.label_2.setMinimumSize(QtCore.QSize(241, 71))
        self.label_2.setMaximumSize(QtCore.QSize(241, 71))
        self.label_2.setStyleSheet("font: 10pt \"Tahoma\";")
        self.label_2.setObjectName("label_2")
        expiredotp.setCentralWidget(self.centralwidget)

        self.retranslateUi(expiredotp)
        QtCore.QMetaObject.connectSlotsByName(expiredotp)

    def retranslateUi(self, expiredotp):
        _translate = QtCore.QCoreApplication.translate
        expiredotp.setWindowTitle(_translate("expiredotp", "OTP Expired"))
        self.ok_otpexpired.setText(_translate("expiredotp", "OK"))
        self.label_2.setText(_translate("expiredotp", "Invalid Registration!\n"
"\n"
"Your OTP has expired. Please try again."))
