# Form implementation generated from reading ui file 'c:\Users\ryanj\OneDrive\Desktop\PD2gui\notif_ui\failed_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt6 import QtCore, QtGui, QtWidgets

MAIN_PATH = os.getcwd()
IMAGES_PATH = os.path.join(MAIN_PATH, 'image')


class Ui_failed_win(object):
    def setupUi(self, failed_win):
        failed_win.setObjectName("failed_win")
        failed_win.resize(370, 200)
        failed_win.setMinimumSize(QtCore.QSize(370, 200))
        failed_win.setMaximumSize(QtCore.QSize(370, 200))
        self.centralwidget = QtWidgets.QWidget(parent=failed_win)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 111, 111))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(os.path.join(IMAGES_PATH, "warning.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.ok_failedbtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ok_failedbtn.setGeometry(QtCore.QRect(270, 150, 81, 41))
        self.ok_failedbtn.setObjectName("ok_failedbtn")
        self.tofillupfailed = QtWidgets.QLabel(parent=self.centralwidget)
        self.tofillupfailed.setGeometry(QtCore.QRect(130, 50, 241, 71))
        self.tofillupfailed.setStyleSheet("font: 10pt \"Tahoma\";")
        self.tofillupfailed.setText("")
        self.tofillupfailed.setObjectName("tofillupfailed")
        failed_win.setCentralWidget(self.centralwidget)

        self.retranslateUi(failed_win)
        QtCore.QMetaObject.connectSlotsByName(failed_win)

    def retranslateUi(self, failed_win):
        _translate = QtCore.QCoreApplication.translate
        failed_win.setWindowTitle(_translate("failed_win", "IMPORTANT!!"))
        self.ok_failedbtn.setText(_translate("failed_win", "OK"))
