# Form implementation generated from reading ui file 'c:\Users\ryanj\OneDrive\Desktop\PD2gui\notif_ui\logout_win.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt6 import QtCore, QtGui, QtWidgets
MAIN_PATH = os.getcwd()
IMAGES_PATH = os.path.join(MAIN_PATH, 'image')


class Ui_logout_win(object):
    def setupUi(self, logout_win):
        logout_win.setObjectName("logout_win")
        logout_win.resize(370, 200)
        logout_win.setMinimumSize(QtCore.QSize(370, 200))
        logout_win.setMaximumSize(QtCore.QSize(370, 200))
        self.centralwidget = QtWidgets.QWidget(parent=logout_win)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 10, 81, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(os.path.join(IMAGES_PATH, "question.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.yes_logout = QtWidgets.QPushButton(parent=self.centralwidget)
        self.yes_logout.setGeometry(QtCore.QRect(90, 140, 81, 41))
        self.yes_logout.setObjectName("yes_logout")
        self.txtlogout = QtWidgets.QLabel(parent=self.centralwidget)
        self.txtlogout.setGeometry(QtCore.QRect(80, 80, 221, 71))
        self.txtlogout.setStyleSheet("font: 700 10pt \"Tahoma\";")
        self.txtlogout.setObjectName("txtlogout")
        self.cancel_logout = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cancel_logout.setGeometry(QtCore.QRect(200, 140, 81, 41))
        self.cancel_logout.setObjectName("cancel_logout")
        logout_win.setCentralWidget(self.centralwidget)

        self.retranslateUi(logout_win)
        QtCore.QMetaObject.connectSlotsByName(logout_win)

    def retranslateUi(self, logout_win):
        _translate = QtCore.QCoreApplication.translate
        logout_win.setWindowTitle(_translate("logout_win", "Logout"))
        self.yes_logout.setText(_translate("logout_win", "Yes"))
        self.txtlogout.setText(_translate("logout_win", "Are you sure you want to logout?"))
        self.cancel_logout.setText(_translate("logout_win", "Cancel"))
