# Form implementation generated from reading ui file 'c:\Users\ryanj\OneDrive\Desktop\PD2gui\notif_ui\success_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt6 import QtCore, QtGui, QtWidgets

MAIN_PATH = os.getcwd()
IMAGES_PATH = os.path.join(MAIN_PATH, 'image')


class Ui_success_win(object):
    def setupUi(self, success_win):
        success_win.setObjectName("success_win")
        success_win.resize(370, 200)
        success_win.setMinimumSize(QtCore.QSize(370, 200))
        success_win.setMaximumSize(QtCore.QSize(370, 200))
        self.centralwidget = QtWidgets.QWidget(parent=success_win)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 111, 111))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(os.path.join(IMAGES_PATH, "checked.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.ok_backlogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ok_backlogin.setGeometry(QtCore.QRect(270, 150, 81, 41))
        self.ok_backlogin.setObjectName("ok_backlogin")
        self.tofillupsuccess = QtWidgets.QLabel(parent=self.centralwidget)
        self.tofillupsuccess.setGeometry(QtCore.QRect(130, 50, 241, 71))
        self.tofillupsuccess.setStyleSheet("font: 10pt \"Tahoma\";")
        self.tofillupsuccess.setText("")
        self.tofillupsuccess.setObjectName("tofillupsuccess")
        success_win.setCentralWidget(self.centralwidget)

        self.retranslateUi(success_win)
        QtCore.QMetaObject.connectSlotsByName(success_win)

    def retranslateUi(self, success_win):
        _translate = QtCore.QCoreApplication.translate
        success_win.setWindowTitle(_translate("success_win", "IMPORTANT!!"))
        self.ok_backlogin.setText(_translate("success_win", "OK"))
