# Form implementation generated from reading ui file 'c:\Users\ryanj\OneDrive\Desktop\PD2gui\notif_ui\warning_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt6 import QtCore, QtGui, QtWidgets

MAIN_PATH = os.getcwd()
IMAGES_PATH = os.path.join(MAIN_PATH, 'image')

class Ui_alert_win(object):
    def setupUi(self, alert_win):
        alert_win.setObjectName("alert_win")
        alert_win.resize(460, 230)
        alert_win.setMinimumSize(QtCore.QSize(460, 230))
        alert_win.setMaximumSize(QtCore.QSize(460, 230))
        self.centralwidget = QtWidgets.QWidget(parent=alert_win)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 141, 141))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(os.path.join(IMAGES_PATH, "alert.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.tofillupsuccess = QtWidgets.QLabel(parent=self.centralwidget)
        self.tofillupsuccess.setGeometry(QtCore.QRect(150, 50, 301, 91))
        self.tofillupsuccess.setStyleSheet("font: 10pt \"Tahoma\";")
        self.tofillupsuccess.setObjectName("tofillupsuccess")
        self.ok_proceed = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ok_proceed.setGeometry(QtCore.QRect(340, 160, 101, 51))
        self.ok_proceed.setObjectName("no_proceed")
        alert_win.setCentralWidget(self.centralwidget)

        self.retranslateUi(alert_win)
        QtCore.QMetaObject.connectSlotsByName(alert_win)

    def retranslateUi(self, alert_win):
        _translate = QtCore.QCoreApplication.translate
        alert_win.setWindowTitle(_translate("alert_win", "IMPORTANT!!"))
        self.tofillupsuccess.setText(_translate("alert_win", "The date range you entered is more than an hour.\n"
"\n"
"This might take longer than usual to process."))
        self.ok_proceed.setText(_translate("alert_win", "OK"))
