# Form implementation generated from reading ui file 'c:\Users\Ryan\Desktop\PD2gui\notif_ui\warning_param.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import os
from PyQt6 import QtCore, QtGui, QtWidgets

MAIN_PATH = os.getcwd()
IMAGES_PATH = os.path.join(MAIN_PATH, 'image')

class Ui_param_win(object):
    def setupUi(self, param_win):
        param_win.setObjectName("param_win")
        param_win.resize(460, 230)
        param_win.setMinimumSize(QtCore.QSize(460, 230))
        param_win.setMaximumSize(QtCore.QSize(460, 230))
        self.centralwidget = QtWidgets.QWidget(parent=param_win)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 141, 141))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(os.path.join(IMAGES_PATH, "warning.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.tofillupsuccess = QtWidgets.QLabel(parent=self.centralwidget)
        self.tofillupsuccess.setGeometry(QtCore.QRect(180, 20, 301, 151))
        self.tofillupsuccess.setStyleSheet("font: 10pt \"Tahoma\";")
        self.tofillupsuccess.setObjectName("tofillupsuccess")
        self.no_proceed = QtWidgets.QPushButton(parent=self.centralwidget)
        self.no_proceed.setGeometry(QtCore.QRect(340, 170, 101, 51))
        self.no_proceed.setObjectName("no_proceed")
        param_win.setCentralWidget(self.centralwidget)

        self.retranslateUi(param_win)
        QtCore.QMetaObject.connectSlotsByName(param_win)

    def retranslateUi(self, param_win):
        _translate = QtCore.QCoreApplication.translate
        param_win.setWindowTitle(_translate("param_win", "IMPORTANT!!"))
        self.tofillupsuccess.setText(_translate("param_win", "Invalid filtering input(s):\n"
"\n"
"Weapon\n"
"Upper Clothing\n"
"Upper Clothing Color\n"
"Lower Clothing\n"
"Lower Clothing Color"))
        self.no_proceed.setText(_translate("param_win", "OK"))
