# Form implementation generated from reading ui file 'c:\Users\ryanj\OneDrive\Desktop\PD2gui\main_uis\login - Copy.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QIcon

MAIN_PATH = os.getcwd()
IMAGES_PATH = os.path.join(MAIN_PATH, 'image')
MAIN_UIS = os.path.join(MAIN_PATH, 'main_uis')

class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(1453, 768)
        self.centralwidget = QtWidgets.QWidget(parent=Login)
        self.centralwidget.setStyleSheet("#centralwidget {\n"
"    border-image: url('image/bgcolor.png');\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(900, 750))
        self.widget.setStyleSheet("image: url('image/10077-removebg.png');")
        self.widget.setObjectName("widget")
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.loginform = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginform.sizePolicy().hasHeightForWidth())
        self.loginform.setSizePolicy(sizePolicy)
        self.loginform.setStyleSheet("background-color: rgb(4, 76, 130);;\n"
"border-radius: 25px;")
        self.loginform.setObjectName("loginform")
        self.gridLayout = QtWidgets.QGridLayout(self.loginform)
        self.gridLayout.setContentsMargins(55, 60, 55, 150)
        self.gridLayout.setObjectName("gridLayout")
        self.forgotpasstxt = QtWidgets.QLabel(parent=self.loginform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forgotpasstxt.sizePolicy().hasHeightForWidth())
        self.forgotpasstxt.setSizePolicy(sizePolicy)
        self.forgotpasstxt.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.forgotpasstxt.setStyleSheet("font: 10pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.forgotpasstxt.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.forgotpasstxt.setObjectName("forgotpasstxt")
        self.gridLayout.addWidget(self.forgotpasstxt, 11, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight)
        self.usernamelogin = QtWidgets.QLineEdit(parent=self.loginform)
        self.usernamelogin.setAutoFillBackground(False)
        self.usernamelogin.setStyleSheet("background-color: rgb(122, 171, 200);\n"
"font: 11pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"padding: 15px;")
        self.usernamelogin.setText("")
        self.usernamelogin.setMaxLength(30)
        self.usernamelogin.setFrame(True)
        self.usernamelogin.setClearButtonEnabled(False)
        self.usernamelogin.setObjectName("usernamelogin")
        self.gridLayout.addWidget(self.usernamelogin, 3, 0, 1, 1)
        self.loginicon = QtWidgets.QLabel(parent=self.loginform)
        self.loginicon.setMinimumSize(QtCore.QSize(141, 141))
        self.loginicon.setStyleSheet("image: url('image/key.png');")
        self.loginicon.setText("")
        self.loginicon.setScaledContents(True)
        self.loginicon.setObjectName("loginicon")
        self.gridLayout.addWidget(self.loginicon, 1, 0, 1, 1)
        self.loginbutton = QtWidgets.QPushButton(parent=self.loginform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginbutton.sizePolicy().hasHeightForWidth())
        self.loginbutton.setSizePolicy(sizePolicy)
        self.loginbutton.setMinimumSize(QtCore.QSize(357, 60))
        self.loginbutton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.loginbutton.setAutoFillBackground(False)
        self.loginbutton.setStyleSheet("#loginbutton{\n"
"background-color: rgb(122, 171, 200);\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"color: white;\n"
"}\n"
"\n"
"#loginbutton:Hover{\n"
"background-color: rgb(16, 170, 215);\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"color: white;\n"
"}\n"
"\n"
"#loginbutton:Pressed {\n"
"background-color: rgb(16, 170, 163);\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"color: white;\n"
"}")
        self.loginbutton.setChecked(False)
        self.loginbutton.setAutoDefault(True)
        self.loginbutton.setObjectName("loginbutton")
        self.gridLayout.addWidget(self.loginbutton, 10, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(50, 20, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.accntmsgtxt = QtWidgets.QLabel(parent=self.loginform)
        self.accntmsgtxt.setStyleSheet("font: 10pt \"Tahoma\"; color: rgb(255, 255, 255);")
        self.accntmsgtxt.setObjectName("accntmsgtxt")
        self.horizontalLayout.addWidget(self.accntmsgtxt, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.registertxt = QtWidgets.QLabel(parent=self.loginform)
        self.registertxt.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.registertxt.setStyleSheet("font: 700 10pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.registertxt.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.registertxt.setObjectName("registertxt")
        self.horizontalLayout.addWidget(self.registertxt)
        self.gridLayout.addLayout(self.horizontalLayout, 12, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.passwordlogin = QtWidgets.QLineEdit(parent=self.loginform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordlogin.sizePolicy().hasHeightForWidth())
        self.passwordlogin.setSizePolicy(sizePolicy)
        self.passwordlogin.setAutoFillBackground(False)
        self.passwordlogin.setStyleSheet("background-color: rgb(122, 171, 200);\n"
"font: 11pt \"Tahoma\";\n"
"padding: 15px;\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-top-right-radius: 0px;\n"
"border-bottom-right-radius: 0px;")
        self.passwordlogin.setText("")
        self.passwordlogin.setMaxLength(30)
        self.passwordlogin.setFrame(True)
        self.passwordlogin.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordlogin.setClearButtonEnabled(False)
        self.passwordlogin.setObjectName("passwordlogin")
        self.horizontalLayout_3.addWidget(self.passwordlogin)
        self.revealpass = QtWidgets.QLabel(parent=self.loginform)
        self.revealpass.setMinimumSize(QtCore.QSize(30, 30))
        self.revealpass.setMaximumSize(QtCore.QSize(41, 50))
        self.revealpass.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.revealpass.setAutoFillBackground(False)
        self.revealpass.setStyleSheet("#revealpass{\n"
"image: url('image/invisible.png');\n"
"width: 70px;\n"
"height: auto;\n"
"background-color: rgb(122, 171, 200);\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"}")
        self.revealpass.setText("")
        self.revealpass.setObjectName("revealpass")
        self.horizontalLayout_3.addWidget(self.revealpass)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 0, 1, 1)
        self.loginmsgtxt = QtWidgets.QLabel(parent=self.loginform)
        self.loginmsgtxt.setStyleSheet("font: 700 18pt \"Tahoma\"; color: rgb(255, 255, 255);")
        self.loginmsgtxt.setObjectName("loginmsgtxt")
        self.gridLayout.addWidget(self.loginmsgtxt, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 6, 0, 1, 1)
        self.gridLayout_2.addWidget(self.loginform, 0, 1, 1, 1)
        Login.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)
        Login.setTabOrder(self.usernamelogin, self.passwordlogin)
        Login.setTabOrder(self.passwordlogin, self.loginbutton)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        Login.setWindowIcon(QIcon("image/inquest.png"))
        self.forgotpasstxt.setText(_translate("Login", "Forgot Password?"))
        self.usernamelogin.setPlaceholderText(_translate("Login", "Username or Email"))
        self.loginbutton.setText(_translate("Login", "Login"))
        self.accntmsgtxt.setText(_translate("Login", "Don\'t have an account?"))
        self.registertxt.setText(_translate("Login", "Register here."))
        self.passwordlogin.setPlaceholderText(_translate("Login", "Password"))
        self.loginmsgtxt.setText(_translate("Login", "Login to access your account"))
