# Form implementation generated from reading ui file 'c:\Users\ryanj\OneDrive\Desktop\PD2gui\main_uis\register.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(600, 800)
        Register.setMinimumSize(QtCore.QSize(580, 800))
        Register.setMaximumSize(QtCore.QSize(600, 800))
        Register.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=Register)
        self.centralwidget.setStyleSheet("#centralwidget {\n"
"    background-color: rgb(4, 76, 130);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.registerform = QtWidgets.QWidget(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.registerform.sizePolicy().hasHeightForWidth())
        self.registerform.setSizePolicy(sizePolicy)
        self.registerform.setStyleSheet("background-color: rgb(4, 76, 130);\n"
"border-radius: 25px;")
        self.registerform.setObjectName("registerform")
        self.gridLayout = QtWidgets.QGridLayout(self.registerform)
        self.gridLayout.setContentsMargins(70, 60, 70, 120)
        self.gridLayout.setObjectName("gridLayout")
        self.regmsgtxt = QtWidgets.QLabel(parent=self.registerform)
        self.regmsgtxt.setStyleSheet("font: 700 25pt \"Tahoma\";\n"
"color: white;")
        self.regmsgtxt.setObjectName("regmsgtxt")
        self.gridLayout.addWidget(self.regmsgtxt, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.userfirstanme = QtWidgets.QLineEdit(parent=self.registerform)
        self.userfirstanme.setAutoFillBackground(False)
        self.userfirstanme.setStyleSheet("background-color: rgb(122, 171, 200);\n"
"font: 11pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"padding: 15px;")
        self.userfirstanme.setText("")
        self.userfirstanme.setMaxLength(30)
        self.userfirstanme.setFrame(True)
        self.userfirstanme.setClearButtonEnabled(False)
        self.userfirstanme.setObjectName("userfirstanme")
        self.horizontalLayout_2.addWidget(self.userfirstanme)
        self.userlastname = QtWidgets.QLineEdit(parent=self.registerform)
        self.userlastname.setAutoFillBackground(False)
        self.userlastname.setStyleSheet("background-color: rgb(122, 171, 200);\n"
"font: 11pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"padding: 15px;")
        self.userlastname.setText("")
        self.userlastname.setMaxLength(30)
        self.userlastname.setFrame(True)
        self.userlastname.setClearButtonEnabled(False)
        self.userlastname.setObjectName("userlastname")
        self.horizontalLayout_2.addWidget(self.userlastname)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.usernamereg = QtWidgets.QLineEdit(parent=self.registerform)
        self.usernamereg.setAutoFillBackground(False)
        self.usernamereg.setStyleSheet("background-color: rgb(122, 171, 200);\n"
"font: 11pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"padding: 15px;")
        self.usernamereg.setText("")
        self.usernamereg.setMaxLength(30)
        self.usernamereg.setFrame(True)
        self.usernamereg.setClearButtonEnabled(False)
        self.usernamereg.setObjectName("usernamereg")
        self.gridLayout.addWidget(self.usernamereg, 3, 0, 1, 1)
        self.useremail = QtWidgets.QLineEdit(parent=self.registerform)
        self.useremail.setAutoFillBackground(False)
        self.useremail.setStyleSheet("background-color: rgb(122, 171, 200);\n"
"font: 11pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"padding: 15px;")
        self.useremail.setText("")
        self.useremail.setMaxLength(30)
        self.useremail.setFrame(True)
        self.useremail.setClearButtonEnabled(False)
        self.useremail.setObjectName("useremail")
        self.gridLayout.addWidget(self.useremail, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.passwordreg = QtWidgets.QLineEdit(parent=self.registerform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordreg.sizePolicy().hasHeightForWidth())
        self.passwordreg.setSizePolicy(sizePolicy)
        self.passwordreg.setAutoFillBackground(False)
        self.passwordreg.setStyleSheet("background-color: rgb(122, 171, 200);\n"
"font: 11pt \"Tahoma\";\n"
"padding: 15px;\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-top-right-radius: 0px;\n"
"border-bottom-right-radius: 0px;")
        self.passwordreg.setText("")
        self.passwordreg.setMaxLength(30)
        self.passwordreg.setFrame(True)
        self.passwordreg.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordreg.setClearButtonEnabled(False)
        self.passwordreg.setObjectName("passwordreg")
        self.horizontalLayout_3.addWidget(self.passwordreg)
        self.revealregpass = QtWidgets.QLabel(parent=self.registerform)
        self.revealregpass.setMinimumSize(QtCore.QSize(30, 30))
        self.revealregpass.setMaximumSize(QtCore.QSize(41, 50))
        self.revealregpass.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.revealregpass.setAutoFillBackground(False)
        self.revealregpass.setStyleSheet("#revealregpass{\n"
"image: url('image/invisible.png');\n"
"width: 70px;\n"
"height: auto;\n"
"background-color: rgb(122, 171, 200);\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"}")
        self.revealregpass.setText("")
        self.revealregpass.setObjectName("revealregpass")
        self.horizontalLayout_3.addWidget(self.revealregpass)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.passwordregconf = QtWidgets.QLineEdit(parent=self.registerform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordregconf.sizePolicy().hasHeightForWidth())
        self.passwordregconf.setSizePolicy(sizePolicy)
        self.passwordregconf.setAutoFillBackground(False)
        self.passwordregconf.setStyleSheet("background-color: rgb(122, 171, 200);\n"
"font: 11pt \"Tahoma\";\n"
"padding: 15px;\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-top-right-radius: 0px;\n"
"border-bottom-right-radius: 0px;")
        self.passwordregconf.setText("")
        self.passwordregconf.setMaxLength(30)
        self.passwordregconf.setFrame(True)
        self.passwordregconf.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordregconf.setClearButtonEnabled(False)
        self.passwordregconf.setObjectName("passwordregconf")
        self.horizontalLayout_4.addWidget(self.passwordregconf)
        self.revealconfpass = QtWidgets.QLabel(parent=self.registerform)
        self.revealconfpass.setMinimumSize(QtCore.QSize(30, 30))
        self.revealconfpass.setMaximumSize(QtCore.QSize(41, 50))
        self.revealconfpass.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.revealconfpass.setAutoFillBackground(False)
        self.revealconfpass.setStyleSheet("#revealconfpass{\n"
"image: url('image/invisible.png');\n"
"width: 70px;\n"
"height: auto;\n"
"background-color: rgb(122, 171, 200);\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"}")
        self.revealconfpass.setText("")
        self.revealconfpass.setObjectName("revealconfpass")
        self.horizontalLayout_4.addWidget(self.revealconfpass)
        self.gridLayout.addLayout(self.horizontalLayout_4, 6, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 7, 0, 1, 1)
        self.registerbutton = QtWidgets.QPushButton(parent=self.registerform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.registerbutton.sizePolicy().hasHeightForWidth())
        self.registerbutton.setSizePolicy(sizePolicy)
        self.registerbutton.setMinimumSize(QtCore.QSize(351, 61))
        self.registerbutton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.registerbutton.setAutoFillBackground(False)
        self.registerbutton.setStyleSheet("#registerbutton{\n"
"background-color: rgb(122, 171, 200);\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"color: white;\n"
"}\n"
"\n"
"#registerbutton:Hover{\n"
"background-color: rgb(16, 170, 215);\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"color: white;\n"
"}\n"
"\n"
"#registerbutton:Pressed {\n"
"background-color: rgb(16, 170, 163);\n"
"font: 700 14pt \"Tahoma\";\n"
"border-radius: 10px;\n"
"color: white;\n"
"}")
        self.registerbutton.setChecked(False)
        self.registerbutton.setObjectName("registerbutton")
        self.gridLayout.addWidget(self.registerbutton, 9, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 10, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(50, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.alrdyaccttxt = QtWidgets.QLabel(parent=self.registerform)
        self.alrdyaccttxt.setStyleSheet("font: 10pt \"Tahoma\";\n"
"color: white;")
        self.alrdyaccttxt.setObjectName("alrdyaccttxt")
        self.horizontalLayout.addWidget(self.alrdyaccttxt)
        self.loginheretxt = QtWidgets.QLabel(parent=self.registerform)
        self.loginheretxt.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.loginheretxt.setStyleSheet("font: 700 10pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.loginheretxt.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.loginheretxt.setWordWrap(False)
        self.loginheretxt.setObjectName("loginheretxt")
        self.horizontalLayout.addWidget(self.loginheretxt)
        self.gridLayout.addLayout(self.horizontalLayout, 11, 0, 1, 1)
        self.gridLayout_2.addWidget(self.registerform, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget, 0, 0, 1, 1)
        Register.setCentralWidget(self.centralwidget)

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "Register"))
        self.regmsgtxt.setText(_translate("Register", "REGISTER"))
        self.userfirstanme.setPlaceholderText(_translate("Register", "First Name"))
        self.userlastname.setPlaceholderText(_translate("Register", "Last Name"))
        self.usernamereg.setPlaceholderText(_translate("Register", "Username"))
        self.useremail.setPlaceholderText(_translate("Register", "Email Address"))
        self.passwordreg.setPlaceholderText(_translate("Register", "Password"))
        self.passwordregconf.setPlaceholderText(_translate("Register", "Confirm Password"))
        self.registerbutton.setText(_translate("Register", "Submit"))
        self.alrdyaccttxt.setText(_translate("Register", "Already have an account?"))
        self.loginheretxt.setText(_translate("Register", "Login here."))
